title: Jiayi He
url: "https://ivy3h.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "h"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - Publications: "Publications"
   link: "publications"
 - Awards & Service: "Awards & Service"
   link: "Awards & Service"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
   
